name: Create Database and User

on:
  workflow_dispatch:
    inputs:
      database_name:
        description: 'Database name to create (without prefix)'
        required: true
        type: string
      db_user:
        description: 'Database user to create (without prefix)'
        required: true
        type: string
      db_password:
        description: 'Password for the database user'
        required: true
        type: string

jobs:
  create-database:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH and Environment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 89.58.46.66 >> ~/.ssh/known_hosts

      - name: Create Database and User in cPanel
        run: |
          # Add 'appmed_' prefix to the database name and user
          db_name="appmed_${{ github.event.inputs.database_name }}"
          db_user="appmed_${{ github.event.inputs.db_user }}"

          # Create Database in cPanel
          response=$(curl -u ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }} \
            "https://cpanel.app-med.com:2083/execute/MySQL/create_database?name=$db_name")
          echo "Database creation response: $response"

          # Create Database User in cPanel
          response=$(curl -u ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }} \
            "https://cpanel.app-med.com:2083/execute/MySQL/add_user?name=$db_user&password=${{ github.event.inputs.db_password }}")
          echo "Database user creation response: $response"

          # Grant Database User Permissions
          response=$(curl -u ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }} \
            "https://cpanel.app-med.com:2083/execute/MySQL/add_user_to_database?user=$db_user&database=$db_name")
          echo "Grant user permissions response: $response"
