name: Deploy to Subdomain

on:
  workflow_dispatch:
    inputs:
      subdomain:
        description: 'Subdomain to create'
        required: true
        type: string
      database_name:
        description: 'Database name to create (without prefix)'
        required: true
        type: string
      db_user:
        description: 'Database user to create (without prefix)'
        required: true
        type: string
      db_password:
        description: 'Password for the database user'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 89.58.46.66 >> ~/.ssh/known_hosts

      - name: Create Subdomain, Database, and User
        run: |
          # Create Subdomain in cPanel
          curl -u ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }} \
            "https://cpanel.app-med.com:2083/execute/SubDomain/addsubdomain?domain=${{ github.event.inputs.subdomain }}.app-med.com&rootdomain=app-med.com"
          
          # Add 'appmed_' prefix to the database name and user
          db_name="appmed_${{ github.event.inputs.database_name }}"
          db_user="appmed_${{ github.event.inputs.db_user }}"

          # Create Database in cPanel
          curl -u ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }} \
            "https://cpanel.app-med.com:2083/execute/MySQL/create_database?name=$db_name"
          
          # Create Database User in cPanel
          curl -u ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }} \
            "https://cpanel.app-med.com:2083/execute/MySQL/add_user?name=$db_user&password=${{ github.event.inputs.db_password }}"
          
          # Grant Database User Permissions
          curl -u ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }} \
            "https://cpanel.app-med.com:2083/execute/MySQL/add_user_to_database?user=$db_user&database=$db_name"
          
          # Create DNS Record in Cloudflare
          curl -X POST "https://api.cloudflare.com/client/v4/zones/YOUR_ZONE_ID/dns_records" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"type":"A","name":"${{ github.event.inputs.subdomain }}.app-med.com","content":"89.58.46.66","ttl":3600}'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CPANEL_USERNAME: ${{ secrets.CPANEL_USERNAME }}
          CPANEL_PASSWORD: ${{ secrets.CPANEL_PASSWORD }}

      - name: Deploy Code to Subdomain
        run: |
          ssh -o StrictHostKeyChecking=no appmed@89.58.46.66 << 'EOF'
            set -e  # Exit on error

            echo "Creating the subdomain directory..."
            mkdir -p /home/appmed/public_html/${{ github.event.inputs.subdomain }}.app-med.com
            
            echo "Navigating to the subdomain folder..."
            cd /home/appmed/public_html/${{ github.event.inputs.subdomain }}.app-med.com || { echo "Directory not found"; exit 1; }

            # Check if the directory is a Git repository
            if [ ! -d ".git" ]; then
              echo "Cloning repository..."
              git clone https://github.com/Progtelx-admin/demo-appmed.git . || { echo "Git clone failed"; exit 1; }
            fi
            
            echo "Pulling the latest code from the repository..."
            git pull origin main || { echo "Git pull failed"; exit 1; }
            
            echo "Navigating to the demo directory..."
            cd demo || { echo "Demo directory not found"; exit 1; }

            echo "Installing/updating Composer dependencies..."
            composer update --no-interaction --prefer-dist --optimize-autoloader || { echo "Composer update failed"; exit 1; }
          EOF

      - name: Set up .env file 
        run: |
          ssh -o StrictHostKeyChecking=no appmed@89.58.46.66 << EOF
            cd /home/appmed/public_html/${{ github.event.inputs.subdomain }}.app-med.com/demo

            # Check if .env.example exists
            if [ ! -f .env.example ]; then
              echo ".env.example file not found!"
              exit 1
            fi

            # Create .env file
            cp .env.example .env

            # Check if .env file was created
            if [ ! -f .env ]; then
              echo ".env file not created!"
              exit 1
            fi

            # Add environment variables
            echo "APP_NAME=${{ secrets.APP_NAME }}" >> .env
            echo "APP_ENV=${{ secrets.APP_ENV }}" >> .env
            echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
            echo "APP_URL=https://${{ github.event.inputs.subdomain }}.app-med.com" >> .env
            echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_DATABASE=appmed_${{ github.event.inputs.database_name }}" >> .env
            echo "DB_USERNAME=appmed_${{ github.event.inputs.db_user }}" >> .env
            echo "DB_PASSWORD=${{ github.event.inputs.db_password }}" >> .env
            echo "MAIL_MAILER=${{ secrets.MAIL_MAILER }}" >> .env
            echo "MAIL_HOST=${{ secrets.MAIL_HOST }}" >> .env
            echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
            echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
            echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
            echo "MAIL_ENCRYPTION=${{ secrets.MAIL_ENCRYPTION }}" >> .env
            echo "MAIL_FROM_NAME=${{ secrets.MAIL_FROM_NAME }}" >> .env
            echo "PUSHER_APP_SECRET=${{ secrets.PUSHER_APP_SECRET }}" >> .env
            echo "PUSHER_APP_CLUSTER=${{ secrets.PUSHER_APP_CLUSTER }}" >> .env
            
            # Output the .env file contents (for debugging)
            cat .env
          EOF

      - name: Generate application key
        run: |
          ssh -o StrictHostKeyChecking=no appmed@89.58.46.66 << EOF
            cd /home/appmed/public_html/${{ github.event.inputs.subdomain }}.app-med.com/demo
            php artisan key:generate
          EOF

      - name: Run migrations
        run: |
          ssh -o StrictHostKeyChecking=no appmed@89.58.46.66 << EOF
            cd /home/appmed/public_html/${{ github.event.inputs.subdomain }}.app-med.com/demo
            php artisan migrate --force
          EOF
