name: Deploy to Subdomain

on:
  workflow_dispatch:
    inputs:
      subdomain:
        description: 'Subdomain to create'
        required: true
        type: string
      database_name:
        description: 'Database name to create'
        required: true
        type: string
      db_user:
        description: 'Database user to create'
        required: true
        type: string
      db_password:
        description: 'Password for the database user'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 89.58.46.66 >> ~/.ssh/known_hosts

      - name: Create Subdomain, Database, and User
        run: |
          # Create Subdomain in cPanel
          curl -u ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }} \
            "https://cpanel.app-med.com:2083/execute/SubDomain/addsubdomain?domain=${{ github.event.inputs.subdomain }}.app-med.com&rootdomain=app-med.com"

          # Create Database in cPanel
          curl -u ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }} \
            "https://cpanel.app-med.com:2083/execute/MySQL/create_database?name=${{ github.event.inputs.database_name }}"

          # Create Database User in cPanel
          curl -u ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }} \
            "https://cpanel.app-med.com:2083/execute/MySQL/add_user?name=${{ github.event.inputs.db_user }}&password=${{ github.event.inputs.db_password }}"

          # Grant Database User Permissions
          curl -u ${{ secrets.CPANEL_USERNAME }}:${{ secrets.CPANEL_PASSWORD }} \
            "https://cpanel.app-med.com:2083/execute/MySQL/add_user_to_database?user=${{ github.event.inputs.db_user }}&database=${{ github.event.inputs.database_name }}"

          # Create DNS Record in Cloudflare
          curl -X POST "https://api.cloudflare.com/client/v4/zones/YOUR_ZONE_ID/dns_records" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"type":"A","name":"${{ github.event.inputs.subdomain }}.app-med.com","content":"89.58.46.66","ttl":3600}'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CPANEL_USERNAME: ${{ secrets.CPANEL_USERNAME }}
          CPANEL_PASSWORD: ${{ secrets.CPANEL_PASSWORD }}

      - name: Deploy Code to Subdomain
        run: |
          ssh -o StrictHostKeyChecking=no your_user@89.58.46.66 << 'EOF'
            # Create the subdomain directory
            mkdir -p /home/your_user/public_html/${{ github.event.inputs.subdomain }}.app-med.com
            # Navigate to the subdomain folder
            cd /home/your_user/public_html/${{ github.event.inputs.subdomain }}.app-med.com
            # Pull the latest code from the repository
            git pull origin main
            # Install/update dependencies and run migrations
            php artisan migrate
          EOF
